server:
  port: '{cipher}459c0c93ceab39c1924bb5addf72f03dc5eedfed7edac44851ecb0a1a1e888c9'
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
    
logging:
  level:
    org.hibernate : info
    org.hibernate.type.descriptor.sql.BasicBinder : trace
    org.hibernate.type.descriptor.sql.BasicExtraator : trace

info:
  app:
    name: "product-provider-config-client-8302"
    description: "product-provider-config-client-8302程序"
    version: "0.0.1"    
